# Generated by Django 5.2 on 2025-04-16 17:51

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0003_categoriaproductobase_0007_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='categoria',
            new_name='categoriaArticulo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='default_user', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
